spring:
  application:
    name: portfolio-manager
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio-manager
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always